### Test root endpoint
GET http://localhost:7070/api/v1/

###

### 1️⃣ Get all candidates
GET http://localhost:7070/api/v1/candidates
Accept: application/json

###

### 2️⃣ Get candidate by ID
GET http://localhost:7070/api/v1/candidates/1
Accept: application/json

###

### 3️⃣ Create a new candidate
POST http://localhost:7070/api/v1/candidates
Content-Type: application/json

{
  "candidateName": "Alice",
  "phone": 12345678,
  "educationBackground": "Master in Computer Science",
  "skills": [
    {
      "id": 3,
      "skillName": "Test",
      "category": "TESTING",
      "description": "Tools and frameworks for testing and QA"
    }
  ]
}

###

### 4️⃣ Update existing candidate
PUT http://localhost:7070/api/v1/candidates/3
Content-Type: application/json

{
  "candidateName": "Alice",
  "phone": 98765210,
  "educationBackground": "Master in Computer Science",
  "skills": [
    {
      "id": 3,
      "skillName": "Test",
      "category": "TESTING",
      "description": "Tools and frameworks for testing and QA"
    }
  ]
}

###

### 5️⃣ Attach a skill to an existing candidate
PUT http://localhost:7070/api/v1/candidates/1/skills/2
Accept: application/json

###

### Get candidates by category

GET http://localhost:7070/api/v1/candidates?category=frontend
Accept: application/json

###

### 6️⃣ Delete a candidate
DELETE http://localhost:7070/api/v1/candidates/1
Accept: application/json

###
